### ISSUE TITLE
Cant download v11 version

### ISSUE THREAD

**Issue by Peach774** [MAClavell/GM-Token-Drag-Visibility-v2#2]
The only available manifest file is from 2.2.2 - I cant download this for v11

**Comment by MAClavell** [comment]
Think I fixed it by messing with package versions on the Foundry website. Can you try downloading it from Foundry again first? If that doesn't work you can use this direct manifest for the v11 version https://raw.githubusercontent.com/MAClavell/GM-Token-Drag-Visibility-v2/2.2.1/module.json. Please get back to me with what works.

**Comment by Peach774** [comment]
Yep - works through foundry now - thank you!
